apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
spec:
  template:
    metadata:
      annotations:
        checksum/config: "v2"    # Bump this value
    spec:
      containers:
      - name: nginx
        env:
        - name: MY_NEW_ENV_VAR
          value: "my-new-value"