apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
spec:
  template:
    spec:
      containers:
      - name: nginx
        env:
        - name: MY_NEW_ENV_VAR
          value: "my-new-value"