apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
spec:
  template:
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        securityContext:
          capabilities:
            add: ["NET_BIND_SERVICE"]